import { copyFile, mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { transform as Transform } from "esbuild";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.resolve(scriptDirectory, "..");
const sourceDirectory = path.join(projectDirectory, "src");
const outputDirectory = path.join(projectDirectory, "dist");
const cleanOnly = process.argv.includes("--clean");

async function main() {
  await rm(outputDirectory, { recursive: true, force: true });

  if (cleanOnly) {
    console.log("CTFramework dist directory cleaned.");
    return;
  }

  await copyDirectory(sourceDirectory, outputDirectory);
  await writeFile(
    path.join(outputDirectory, "package.json"),
    JSON.stringify({ type: "module" }, null, 2) + "\n"
  );
  const bundlePath = path.join(outputDirectory, "ctframework.bundle.js");
  const bundle = await CreateBundle();
  const minifiedBundlePath = path.join(outputDirectory, "ctframework.bundle.min.js");
  await writeFile(bundlePath, bundle);
  const minified = await Transform(bundle, { minify: true, keepNames: true, format: "esm", target: "es2022" });
  await writeFile(minifiedBundlePath, minified.code);
  console.log("CTFramework build complete. Module distribution and standalone bundles are in dist/.");
}

async function CreateBundle() {
  const modulePaths = await GetJavaScriptFiles(sourceDirectory);
  const moduleContents = await Promise.all(
    modulePaths.map(async (modulePath) => {
      const moduleId = ToModuleId(modulePath);
      const source = await readFile(modulePath, "utf8");
      return { moduleId, source };
    })
  );
  const defaultStyles = await readFile(path.join(sourceDirectory, "styles", "Default.css"), "utf8");
  const publicExports = await GetPublicExports();
  const moduleFactories = moduleContents
    .map(({ moduleId, source }) => `    ${JSON.stringify(moduleId)}: (__exports, __require) => {\n${TransformModule(source, moduleId)}\n    }`)
    .join(",\n");
  const namedExports = publicExports
    .filter((name) => name !== "default")
    .map((name) => `export const ${name} = __ctframeworkBundle.${name};`)
    .join("\n");
  const stylesUrl = `data:text/css;charset=utf-8,${encodeURIComponent(MinifyCss(defaultStyles))}`;

  return `// Generated by scripts/build.js. Do not edit directly.\nconst __ctframeworkBundle = (() => {\n  const __factories = {\n${moduleFactories}\n  };\n  const __cache = new Map();\n  const __require = (moduleId) => {\n    if (__cache.has(moduleId)) {\n      return __cache.get(moduleId);\n    }\n\n    const __exports = {};\n    __cache.set(moduleId, __exports);\n    __factories[moduleId](__exports, __require);\n    return __exports;\n  };\n\n  const __index = __require("./Index.js");\n  const __publicIndex = {};\n  Object.keys(__index).forEach((key) => {\n    const value = __index[key];\n    __publicIndex[key] = value?.__ctLiveValue || value;\n  });\n  __require("./CTFramework.js").CTFramework.DefaultStylesUrl = ${JSON.stringify(stylesUrl)};\n  return __publicIndex;\n})();\n\nexport default __ctframeworkBundle.default;\n${namedExports}\n`;
}

async function GetJavaScriptFiles(directoryPath) {
  const entries = await readdir(directoryPath, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(directoryPath, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await GetJavaScriptFiles(entryPath)));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".js")) {
      files.push(entryPath);
    }
  }

  return files;
}

async function GetPublicExports() {
  const indexSource = await readFile(path.join(sourceDirectory, "Index.js"), "utf8");
  const exportBlock = indexSource.match(/export\s*\{([\s\S]*?)\};/);
  const names = exportBlock?.[1]
    .split(",")
    .map((name) => name.trim())
    .filter(Boolean) || [];

  return [...names, "default"];
}

function TransformModule(source, moduleId) {
  let importIndex = 0;
  const exportNames = [];
  let defaultExport = null;
  let transformedSource = source.replace(/import\s+\{([\s\S]*?)\}\s+from\s+["']([^"']+)["'];?/g, (_, importedNames, importPath) => {
    const resolvedModuleId = ResolveModuleId(moduleId, importPath);
    const importVariable = `__import${importIndex++}`;
    const bindings = importedNames
      .split(",")
      .map((binding) => binding.trim())
      .filter(Boolean)
      .map((binding) => {
        const [exportedName, localName = exportedName] = binding.split(/\s+as\s+/);
        return `const ${localName} = __CreateLiveImport(${importVariable}, ${JSON.stringify(exportedName)});`;
      })
      .join("\n");

    return `const ${importVariable} = __require(${JSON.stringify(resolvedModuleId)});\n${bindings}`;
  });

  transformedSource = transformedSource.replace(/export\s+(const|class)\s+(\w+)/g, (_, declarationType, name) => {
    exportNames.push(name);
    return `${declarationType} ${name}`;
  });
  transformedSource = transformedSource.replace(/export\s+default\s+(\w+)\s*;/g, (_, name) => {
    defaultExport = name;
    return "";
  });
  transformedSource = transformedSource.replace(/export\s*\{([\s\S]*?)\};/g, (_, names) => {
    names
      .split(",")
      .map((name) => name.trim())
      .filter(Boolean)
      .forEach((name) => {
        const [localName, exportedName = localName] = name.split(/\s+as\s+/);
        exportNames.push({ localName, exportedName });
      });
    return "";
  });

  const assignments = exportNames
    .map((entry) => {
      const localName = typeof entry === "string" ? entry : entry.localName;
      const exportedName = typeof entry === "string" ? entry : entry.exportedName;
      return `__exports.${exportedName} = ${localName};`;
    })
    .join("\n");
  const defaultAssignment = defaultExport ? `\n__exports.default = ${defaultExport};` : "";

  return `      const __CreateLiveImport = (module, name) => new Proxy(function () {}, {\n        get: (_, property) => property === "__ctLiveValue"\n          ? module[name]\n          : property === Symbol.hasInstance\n            ? (value) => value instanceof module[name]\n            : Reflect.get(module[name], property),\n        apply: (_, thisValue, argumentsList) => Reflect.apply(module[name], thisValue, argumentsList),\n        construct: (_, argumentsList, newTarget) => Reflect.construct(module[name], argumentsList, newTarget)\n      });\n${transformedSource}\n${assignments}${defaultAssignment}`;
}

function ResolveModuleId(fromModuleId, importPath) {
  return `./${path.posix.normalize(path.posix.join(path.posix.dirname(fromModuleId), importPath)).replace(/^\.\//, "")}`;
}

function ToModuleId(modulePath) {
  return `./${path.relative(sourceDirectory, modulePath).replaceAll(path.sep, "/")}`;
}

function MinifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .trim();
}

async function copyDirectory(sourcePath, outputPath) {
  await mkdir(outputPath, { recursive: true });

  const entries = await readdir(sourcePath, { withFileTypes: true });

  for (const entry of entries) {
    const sourceEntryPath = path.join(sourcePath, entry.name);
    const outputEntryPath = path.join(outputPath, entry.name);

    if (entry.isDirectory()) {
      await copyDirectory(sourceEntryPath, outputEntryPath);
      continue;
    }

    const sourceStats = await stat(sourceEntryPath);

    if (!sourceStats.isFile()) {
      continue;
    }

    await copyFile(sourceEntryPath, outputEntryPath);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
