import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build as Build, transform as Transform } from "esbuild";

const projectDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirectory = path.join(projectDirectory, "src");
const outputDirectory = path.join(projectDirectory, "dist");

const Main = async () => {
  if (path.relative(projectDirectory, outputDirectory) !== "dist") throw new Error("Invalid output directory.");
  await rm(outputDirectory, { recursive: true, force: true });
  if (process.argv.includes("--clean")) return;

  await mkdir(outputDirectory, { recursive: true });
  await cp(sourceDirectory, outputDirectory, { recursive: true });
  await writeFile(path.join(outputDirectory, "package.json"), '{"type":"module"}\n');
  const css = await Transform(await readFile(path.join(sourceDirectory, "styles/Default.css"), "utf8"), { loader: "css", minify: true, target: "es2022" });
  const stylesUrl = `data:text/css;charset=utf-8,${encodeURIComponent(css.code.trim())}`;
  const entry = `import { CTFramework } from "./src/CTFramework.js";
CTFramework.DefaultStylesUrl = ${JSON.stringify(stylesUrl)};
export * from "./src/Index.js";
export { default } from "./src/Index.js";`;

  for (const minify of [false, true]) {
    await Build({
      stdin: { contents: entry, resolveDir: projectDirectory, sourcefile: "CTFrameworkBundle.js" },
      outfile: path.join(outputDirectory, `ctframework.bundle${minify ? ".min" : ""}.js`),
      bundle: true,
      format: "esm",
      platform: "browser",
      target: "es2022",
      minify,
      keepNames: true,
      banner: { js: "// Generated by scripts/Build.js. Do not edit directly." }
    });
  }
  console.log("CTFramework build complete. Module distribution and standalone bundles are in dist/.");
};

Main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
